### ISSUE TITLE
Morlock does not support image processors or non-filename images

### ISSUE THREAD

**Issue by ralfonso** [tdreyno/morlock.js#17]
https://github.com/tdreyno/morlock.js/blob/master/core/responsive-image.js#L267

If I have an image asset on a CDN, it might not be named like a file on disk. The "path" portion of the url could simply be an id. e.g. `http://cdn.example.com/asset/aaa-bbb-ccc`

Alternatively, if my image is generated via a processor API, the filename meet the "last-dot" requirements for this function. e.g. `http://api.example.com/resize&url=http://blah.com/sweet-photo.jpg&w=1000&h=200`

**Comment by tdreyno** [comment]
`getPath` is configurable and can be replaced with your own implementation. Going to show Paul how to do this right now :)
